import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import "../globals.css";
import NavBar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Feed Pet | Monito",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavBar />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
